### ISSUE TITLE
Fix build on Ubuntu 24

### ISSUE THREAD

**Issue by rubensworks** [rdfostrich/ostrich#9]
CI build on `ubuntu-24.04` (`ubuntu-latest`) fails due to:
```
In file included from /home/runner/work/ostrich/ostrich/src/main/cpp/controller/snapshot_creation_strategy.cc:3:
/home/runner/work/ostrich/ostrich/src/main/cpp/controller/snapshot_creation_strategy.h:9:17: error: ‘uint64_t’ was not declared in this scope
    9 |     std::vector<uint64_t> delta_sizes;
      |                 ^~~~~~~~
/home/runner/work/ostrich/ostrich/src/main/cpp/controller/snapshot_creation_strategy.h:5:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    4 | #include <vector>
  +++ |+#include <cstdint>
```

See https://github.com/LinkedDataFragments/HDT-Node/commit/de0f7ee6fa1f62d5da287954ca3f53e0df40ebc5 for a possible solution.
